name: 'deploy'

on:
  workflow_dispatch:
    inputs:
      git_remote_url:
        description: 'Remote git url'
        required: true
        default: 'ssh://dokku@dokku-foo.northeurope.cloudapp.azure.com:22/appname'
        options:
          dev:
            - 'dev'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_name}}/shebang
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Push to dokku
        uses: dokku/github-action@master
        env:
          GIT_SSH_COMMAND: 'ssh -vvv'
        with:
          #git_push_flags: '-vvv'
          git_remote_url: ${{ github.event.inputs.environment }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
